<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/open-iconic-bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/animate.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/owl.carousel.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/owl.theme.default.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/magnific-popup.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/aos.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/ionicons.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/bootstrap-datepicker.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/jquery.timepicker.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/flaticon.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/icomoon.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/style.css')}}">
